Banco/Controllers/AmigoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.DB;
using WebApplication3.Extensiones;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class AmigoController : Controller
    {
        private AppPruebaContext context;
        public AmigoController()
        {
            context = new AppPruebaContext();
        }
        public IActionResult Index()
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            var amigos = context.Amigos.Include(o => o.User).Where(o => o.IdUserA == userLogged.IdUsuario).ToList();

            return View(amigos);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            var usuarios = context.Users.Where(o => o.IdUsuario != userLogged.IdUsuario).ToList();

            return View(usuarios);
        }

        [HttpGet]
        public IActionResult Solicitud(int IdUsuario)
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            Solicitud solicitud = new Solicitud();
            solicitud.IdUser = userLogged.IdUsuario;
            solicitud.Estado = "Pendiente";
            solicitud.IdUserEnviado = IdUsuario;

            context.Solicitudes.Add(solicitud);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Banco/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.DB;
using WebApplication3.Extensiones;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    [Authorize]
    public class CuentaController : Controller
    {
        private AppPruebaContext context;
        public CuentaController()
        {
            context = new AppPruebaContext();
        }
        public IActionResult Index()
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            var cuenta = context.Cuentas.Where(o => o.IdUsuario == userLogged.IdUsuario).ToList();

            return View(cuenta);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categoria = GetCategorias();
            return View(new Cuenta());
        }
        [HttpPost]
        public IActionResult Create(Cuenta cuenta)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categoria = GetCategorias();
                return View(cuenta);
            }

            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            cuenta.IdUsuario = userLogged.IdUsuario;
            cuenta.LimiteCuenta = cuenta.SaldoInicial;

            context.Cuentas.Add(cuenta);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        private List<String> GetCategorias()
        {
            return new List<string>
            {
                "Propia","Credito"
            };
        }
    }
}

Banco/Controllers/SolicitudController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.DB;
using WebApplication3.Extensiones;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class SolicitudController : Controller
    {
        private AppPruebaContext context;
        public SolicitudController()
        {
            context = new AppPruebaContext();
        }
        public IActionResult Index()
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            var solicitudes = context.Solicitudes.Include(o => o.User).Where(o => o.IdUserEnviado == userLogged.IdUsuario).ToList();

            return View(solicitudes);
        }
        [HttpGet]
        public IActionResult Aceptar(int IdUsuario, int IdSolicitud)
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");

            Amigo amigo = new Amigo();
            Amigo amigo2 = new Amigo();

            amigo.IdUser = userLogged.IdUsuario;
            amigo.IdUserA = IdUsuario;

            amigo2.IdUser = IdUsuario;
            amigo2.IdUserA = userLogged.IdUsuario;

            context.Amigos.Add(amigo);
            context.SaveChanges();

            context.Amigos.Add(amigo2);
            context.SaveChanges();

            var solicitud = context.Solicitudes.Where(o => o.IdSolicitud == IdSolicitud).FirstOrDefault();
            solicitud.Estado = "Aceptada";
            context.Entry(solicitud).State = EntityState.Modified;
            context.SaveChanges();

            return RedirectToAction("Index", "Amigo");
        }
    }
}

Banco/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication3.DB;
using WebApplication3.Extensiones;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class UsuarioController : Controller
    {
        private AppPruebaContext context;
        public UsuarioController()
        {
            context = new AppPruebaContext();
        }
        [HttpGet]
        public IActionResult Index()
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            ViewBag.Usuario = context.Users.Where(o => o.IdUsuario == userLogged.IdUsuario).FirstOrDefault();
            return View();
        }
        [HttpGet]
        public IActionResult Saldo()
        {
            var userLogged = HttpContext.Session.Get<User>("SessionLoggedUser");
            var cuenta = context.Cuentas.Where(o => o.IdUsuario == userLogged.IdUsuario).ToList();
            var usuario = context.Users.Where(o => o.IdUsuario == userLogged.IdUsuario).FirstOrDefault();
            usuario.SaldoTotal = 0;

            foreach (var item in cuenta)
            {
                if (item.Categoria == "Propia")
                {
                    usuario.SaldoTotal += item.SaldoInicial;
                }
                if (item.Categoria == "Credito")
                {
                    var n = item.LimiteCuenta - item.SaldoInicial;
                    usuario.SaldoTotal -= n;
                }
            }
            
            context.Entry(usuario).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Banco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Banco</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Banco</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Index">Cuenta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Saldo">Saldo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transferencia" asp-action="Create">Hacer Transferencia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Amigo" asp-action="Index">Amigos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solicitud" asp-action="Index">Solicitudes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Banco - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>